# Generated by Django 4.2 on 2024-04-16 13:20

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Smoke",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "images",
                    models.FileField(
                        upload_to=main.models.dynamic_path,
                        validators=[main.models.validate_file_extension],
                        verbose_name="",
                    ),
                ),
            ],
        ),
    ]
