# Generated by Django 4.2 on 2024-04-16 13:45

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_smoke"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smoke",
            name="images",
            field=models.FileField(
                upload_to=main.models.dynamic_path2,
                validators=[main.models.validate_file_extension],
                verbose_name="",
            ),
        ),
    ]
