# Generated by Django 4.2 on 2024-05-09 15:33

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_smoke_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrawledImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True, verbose_name="Image URL")),
                (
                    "image",
                    models.ImageField(
                        upload_to=main.models.dynamic_path2, verbose_name="Image"
                    ),
                ),
            ],
        ),
    ]
