# Generated by Django 4.2 on 2024-05-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_crawledimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image_file", models.ImageField(upload_to="images/")),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="CrawledImage",
        ),
    ]
